-- -----------------------------------------------------
-- Schema SUDOCUBE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SUDOCUBE` ;

-- -----------------------------------------------------
-- Schema SUDOCUBE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SUDOCUBE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `SUDOCUBE` ;

